In [164]:
import pandas as pd
import numpy as np

In [165]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [166]:
movies.sample(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
2490,16000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",NaN,8009,"[{""id"": 242, ""name"": ""new york""}, {""id"": 388, ...",en,Highlander,He fought his first battle on the Scottish Hig...,29.253833,"[{""name"": ""Davis-Panzer Productions"", ""id"": 27...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",1986-03-07,5900000,116.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,There can be only one.,Highlander,6.8,624

In [167]:
credits.sample(1)

,movie_id,title,cast,crew
959,9624,On Deadly Ground,"[{""cast_id"": 1, ""character"": ""Forrest Taft"", ""...","[{""credit_id"": ""52fe4513c3a36847f80baed9"", ""de..."

In [168]:
movies = movies.merge(credits , on='title')   #merger both datasets on col title

In [169]:
movies.info() # taking cols = genres, id, keywords, title, cast, crew, overview -- help in our analysis
# language ignored beacuse mostly are english here
# id taken to later use to fetch their posters
# we don't want numerical data more here

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [170]:
movies = movies[['movie_id','original_title','overview','genres','keywords','cast','crew']]

In [171]:
movies.isnull().sum()

movie_id          0
original_title    0
overview          3
genres            0
keywords          0
cast              0
crew              0
dtype: int64

In [172]:
movies.dropna(inplace=True)           #inplace = true -- modifies in original df

In [173]:
movies.duplicated().sum()

0

In [174]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [175]:
import ast

In [176]:
def convert(text):
    L = []
    for i in ast.literal_eval(text):        # to convert string to object
        L.append(i['name']) 
    return L

In [177]:
# Apply the robust convert function
movies['genres'] = movies['genres'].apply(convert)
movies['keywords'] = movies['keywords'].apply(convert)

In [178]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [179]:
movies['cast'] = movies['cast'].apply(convert3)    # taken top 3 chars

In [180]:
movies['cast']

0        [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1           [Johnny Depp, Orlando Bloom, Keira Knightley]
2            [Daniel Craig, Christoph Waltz, Léa Seydoux]
3            [Christian Bale, Michael Caine, Gary Oldman]
4          [Taylor Kitsch, Lynn Collins, Samantha Morton]
                              ...
4804    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4805         [Edward Burns, Kerry Bishé, Marsha Dietlein]
4806           [Eric Mabius, Kristin Booth, Crystal Lowe]
4807            [Daniel Henney, Eliza Coupe, Bill Paxton]
4808    [Drew Barrymore, Brian Herzlinger, Corey Feldman]
Name: cast, Length: 4806, dtype: object

In [181]:
movies.iloc[0].crew

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [182]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [183]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [184]:
movies.head()

,movie_id,original_title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [185]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [186]:
# converting this string to list  # to finally club all cols
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [187]:
movies.head()

,movie_id,original_title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [188]:
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))     #saari spaces hata rhe like name sam mendes -- both will count as diff entities so remove space to make one
    return L1

In [189]:
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)
movies['overview'] = movies['overview'].apply(collapse)
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)

In [190]:
movies.head()

,movie_id,original_title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [191]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [192]:
movies.head()

,movie_id,original_title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [193]:
new_df = movies[['movie_id','original_title','tags']]

In [194]:
new_df.head()

,movie_id,original_title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [196]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))  # convert list to string
new_df.head()

C:\Users\gnish\AppData\Local\Temp\ipykernel_21308\3040553394.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))  # convert list to string

,movie_id,original_title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [198]:
new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())  # recommmended

C:\Users\gnish\AppData\Local\Temp\ipykernel_21308\4164960838.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())  # recommmended

In [201]:
new_df.head()

,movie_id,original_title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [220]:
import nltk

In [224]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [225]:
def stem(text):
    l=[]
    for i in text.split(): #string to list
        l.append(ps.stem(i))

    return " ".join(l)

In [226]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\gnish\AppData\Local\Temp\ipykernel_21308\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [227]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=4000 , stop_words='english')

In [228]:
vector = cv.fit_transform(new_df['tags']).toarray()

In [229]:
print(cv.get_feature_names_out().tolist())

['000', '007', '10', '100', '11', '12', '13', '14', '15', '16', '17', '18', '18th', '19', '1910', '1930', '1940', '1950', '1950s', '1960', '1960s', '1970', '1970s', '1980', '1990', '19th', '19thcenturi', '20', '200', '20th', '24', '25', '30', '3d', '40', '50', '60', '70', 'aaron', 'aaroneckhart', 'abandon', 'abduct', 'abigailbreslin', 'abil', 'abl', 'aboard', 'abov', 'abus', 'academi', 'accept', 'access', 'accid', 'accident', 'accompani', 'accomplish', 'account', 'accus', 'ace', 'achiev', 'act', 'action', 'activ', 'activist', 'actor', 'actress', 'actual', 'adam', 'adamsandl', 'adamshankman', 'adapt', 'add', 'addict', 'adjust', 'admir', 'admit', 'adolesc', 'adopt', 'ador', 'adrienbrodi', 'adult', 'adulteri', 'adulthood', 'advanc', 'adventur', 'adventure', 'advertis', 'advic', 'advis', 'affair', 'affect', 'afghanistan', 'africa', 'african', 'africanamerican', 'aftercreditssting', 'afterlif', 'aftermath', 'ag', 'age', 'agediffer', 'agency', 'agenda', 'agent', 'aggress', 'ago', 'agre', 'ahead', 'aid', 'ail', 'aim', 'air', 'airplan', 'airport', 'aka', 'al', 'alabama', 'alaska', 'albert', 'alcohol', 'alecbaldwin', 'alex', 'ali', 'alic', 'alice', 'alien', 'alieninvas', 'alienlife', 'aliv', 'alive', 'allen', 'alli', 'allianc', 'allow', 'alon', 'alongsid', 'alpacino', 'alreadi', 'alter', 'altern', 'alway', 'alzheimer', 'amanda', 'amandapeet', 'amandaseyfri', 'amateur', 'amaz', 'ambassador', 'ambit', 'ambiti', 'ambul', 'ambush', 'america', 'american', 'americanfootbal', 'amid', 'amidst', 'amnesia', 'amp', 'amus', 'amusementpark', 'amyadam', 'amysmart', 'analyst', 'anarchiccomedi', 'ancient', 'ancientrom', 'ancientworld', 'anderson', 'andi', 'andiemacdowel', 'andrew', 'android', 'andygarcía', 'angel', 'angelabassett', 'angeles', 'angelinajoli', 'anger', 'angle', 'angri', 'ani', 'anim', 'animalattack', 'animalhorror', 'animals', 'ann', 'anna', 'annafari', 'annehathaway', 'annemoss', 'annetteben', 'anni', 'annie', 'announc', 'annual', 'anonym', 'anoth', 'answer', 'ant', 'antholog', 'anthoni', 'anthonyanderson', 'anthonyhopkin', 'anthropomorph', 'anti', 'antihero', 'antoniobandera', 'antonyelchin', 'anyon', 'anyth', 'apart', 'apartheid', 'apartment', 'ape', 'apocalyps', 'apocalypt', 'appar', 'appear', 'appoint', 'appreci', 'apprentic', 'approach', 'april', 'arab', 'archaeologist', 'architect', 'arctic', 'area', 'aren', 'arena', 'argument', 'aris', 'aristocrat', 'arm', 'armi', 'armor', 'armsdeal', 'army', 'arnold', 'arnoldschwarzenegg', 'arrang', 'arrest', 'arriv', 'arrog', 'art', 'arthur', 'artificialintellig', 'artist', 'ash', 'ashley', 'ashleyjudd', 'ashtonkutch', 'asia', 'ask', 'aspir', 'assassin', 'assault', 'assign', 'assist', 'assistant', 'associ', 'assum', 'asteroid', 'astronaut', 'asylum', 'athlet', 'atomicbomb', 'attack', 'attempt', 'attend', 'attent', 'attitud', 'attorney', 'attract', 'audienc', 'audit', 'august', 'aunt', 'austin', 'australia', 'australian', 'author', 'autism', 'auto', 'aveng', 'averag', 'avoid', 'await', 'awaken', 'award', 'away', 'awkward', 'awri', 'awry', 'babe', 'babi', 'baby', 'bachelor', 'backdrop', 'background', 'bad', 'bag', 'bahama', 'bail', 'balanc', 'ball', 'ballet', 'band', 'bandit', 'banish', 'bank', 'banker', 'bankrobberi', 'bar', 'bare', 'bargain', 'barn', 'barney', 'baron', 'barri', 'barrylevinson', 'bas', 'base', 'basebal', 'basedoncomicbook', 'basedongraphicnovel', 'basedonnovel', 'basedonplay', 'basedonstagemus', 'basedontrueev', 'basedontruestori', 'basedontvseri', 'basedonvideogam', 'basedonyoungadultnovel', 'basement', 'basketbal', 'batman', 'battl', 'battle', 'battlefield', 'bay', 'beach', 'bear', 'beast', 'beat', 'beauti', 'beautiful', 'beautifulwoman', 'beauty', 'becam', 'becaus', 'becom', 'becominganadult', 'bed', 'bedroom', 'beer', 'befor', 'befriend', 'began', 'begin', 'behavior', 'belief', 'believ', 'bell', 'bella', 'belong', 'belov', 'ben', 'benaffleck', 'bend', 'beniciodeltoro', 'benjamin', 'benjaminbratt', 'benkingsley', 'bennett', 'benstil', 'bent', 'berlin', 'best', 'bestfriend', 'bet', 'beth', 'betray', 'better', 'betti', 'beverli', 'bibl', 'big', 'bigger', 'biggest', 'biker', 'bikini', 'billi', 'billionair', 'billmurray', 'billpaxton', 'billpullman', 'billybobthornton', 'biographi', 'bird', 'birth', 'birthday', 'bisexu', 'bishop', 'bit', 'bite', 'bitter', 'bizarr', 'black', 'blackmag', 'blackmail', 'blackpeopl', 'blade', 'blame', 'blend', 'blind', 'bliss', 'block', 'blond', 'blood', 'bloodi', 'bloodsplatt', 'bloodthirsti', 'blow', 'blue', 'board', 'boardingschool', 'boat', 'bob', 'bobbi', 'bobbyfarrelli', 'bodi', 'body', 'bodyguard', 'bold', 'bollywood', 'bomb', 'bond', 'bone', 'book', 'border', 'bore', 'boredom', 'born', 'boss', 'boston', 'bound', 'bounti', 'bountyhunt', 'box', 'boxer', 'boy', 'boyfriend', 'boys', 'bradleycoop', 'bradpitt', 'brain', 'brand', 'brave', 'braveri', 'brazil', 'brazilian', 'break', 'breed', 'brendanfras', 'brendangleeson', 'brettratn', 'brian', 'briandepalma', 'bride', 'bridesmaid', 'bridg', 'brief', 'brilliant', 'bring', 'brink', 'britain', 'british', 'britishsecretservic', 'broadcast', 'broadway', 'broke', 'broken', 'broker', 'brook', 'brooklyn', 'brothel', 'brother', 'brotherbrotherrelationship', 'brothers', 'brothersisterrelationship', 'brought', 'brown', 'bruce', 'brucewilli', 'brutal', 'bryansing', 'bu', 'buck', 'bud', 'buddi', 'buddy', 'buddycomedi', 'budget', 'build', 'building', 'built', 'bullet', 'bulli', 'bumbl', 'burglar', 'buri', 'burn', 'bush', 'busi', 'business', 'businessman', 'bust', 'butler', 'buy', 'cabin', 'caesar', 'cage', 'cairo', 'cal', 'california', 'calvin', 'camcord', 'came', 'camera', 'cameraman', 'camerondiaz', 'camp', 'campaign', 'campu', 'canada', 'canadian', 'cancer', 'candid', 'cannib', 'capabl', 'capit', 'captain', 'captiv', 'captur', 'car', 'caraccid', 'carchas', 'carcrash', 'card', 'care', 'career', 'carefre', 'caretak', 'caribbean', 'carjourney', 'carl', 'carlagugino', 'carmen', 'carol', 'carrac', 'carri', 'carrie', 'cartel', 'carter', 'caryelw', 'case', 'caseyaffleck', 'cash', 'casino', 'cast', 'castl', 'cat', 'cataclysm', 'catastroph', 'catch', 'cateblanchett', 'catherinekeen', 'catherinezeta', 'cathol', 'catholic', 'caught', 'caus', 'cave', 'celebr', 'cellphon', 'cemeteri', 'center', 'central', 'centuri', 'centuries', 'century', 'certain', 'chain', 'chainsaw', 'challeng', 'champion', 'championship', 'chanc', 'chance', 'chang', 'channingtatum', 'chao', 'chaos', 'chapter', 'charact', 'character', 'characters', 'charg', 'charismat', 'charl', 'charli', 'charlie', 'charlizetheron', 'charm', 'chase', 'cheat', 'check', 'cheerlead', 'chef', 'chemic', 'cher', 'chicago', 'chicken', 'chief', 'child', 'childabus', 'childhero', 'childhood', 'children', 'chill', 'china', 'chines', 'chip', 'chocol', 'choic', 'choos', 'chosen', 'chri', 'chriscolumbu', 'chrisevan', 'chrishemsworth', 'chrispin', 'chrisrock', 'christ', 'christian', 'christianbal', 'christinaricci', 'christma', 'christmas', 'christmasparti', 'christoph', 'christopherlloyd', 'christopherplumm', 'christopherwalken', 'chronicl', 'chuck', 'church', 'cia', 'cillianmurphi', 'cinema', 'circl', 'circu', 'circuit', 'circumst', 'citi', 'citizen', 'city', 'civil', 'civilian', 'civilwar', 'claim', 'clair', 'clan', 'clark', 'clash', 'class', 'classic', 'classmat', 'classroom', 'claudevandamm', 'clean', 'clear', 'clerk', 'client', 'climat', 'climb', 'clinteastwood', 'cliveowen', 'clock', 'clone', 'close', 'closer', 'clown', 'club', 'clue', 'clutch', 'coach', 'coast', 'cocain', 'code', 'coffin', 'col', 'cold', 'coldwar', 'cole', 'colinfarrel', 'colinfirth', 'collaps', 'colleagu', 'collect', 'collector', 'colleg', 'college', 'collid', 'collis', 'colonel', 'coloni', 'color', 'colorado', 'coma', 'combat', 'combin', 'come', 'comeback', 'comed', 'comedi', 'comedian', 'comedy', 'comfort', 'comic', 'coming', 'comingofag', 'comingout', 'command', 'commando', 'commerci', 'commit', 'common', 'commun', 'community', 'compani', 'companion', 'company', 'compet', 'competit', 'competition', 'complet', 'complex', 'complic', 'compos', 'comput', 'conan', 'concern', 'concert', 'condit', 'confess', 'confid', 'conflict', 'confront', 'confus', 'congress', 'conman', 'connect', 'connel', 'connor', 'conquer', 'consequ', 'consequences', 'conserv', 'consid', 'conspir', 'conspiraci', 'conspiracy', 'constant', 'constantli', 'construct', 'consum', 'contact', 'contain', 'contemporari', 'contend', 'contest', 'continu', 'contract', 'control', 'controversi', 'convent', 'convers', 'convict', 'convinc', 'cook', 'cool', 'cooper', 'cop', 'cope', 'core', 'corner', 'corpor', 'corps', 'corrupt', 'cost', 'costum', 'couldn', 'count', 'countri', 'country', 'countrysid', 'coup', 'coupl', 'couple', 'courag', 'cours', 'court', 'courtcas', 'courteneycox', 'courtroom', 'cousin', 'cover', 'covert', 'cowardli', 'cowboy', 'crack', 'craft', 'craig', 'crash', 'crazi', 'creat', 'creation', 'creativ', 'creator', 'creatur', 'creatures', 'credit', 'crew', 'crime', 'crimefight', 'crimin', 'criminal', 'criminals', 'crisi', 'crisis', 'critic', 'crocodil', 'crook', 'cross', 'crowd', 'crown', 'cruel', 'cruis', 'crusad', 'crush', 'crystal', 'cuba', 'cubagoodingjr', 'cult', 'cultfilm', 'cultur', 'cultureclash', 'cup', 'cure', 'current', 'curs', 'curse', 'custodi', 'custom', 'cut', 'cyberpunk', 'cyborg', 'cynic', 'dad', 'daili', 'dakotafan', 'damag', 'dan', 'danaykroyd', 'danc', 'dancer', 'danger', 'daniel', 'danielcraig', 'danni', 'danny', 'dannydevito', 'dannyglov', 'dare', 'dark', 'darkcomedi', 'darkest', 'dash', 'date', 'daughter', 'dave', 'davi', 'david', 'davidarquett', 'davidduchovni', 'davidfinch', 'day', 'days', 'dccomic', 'dea', 'dead', 'deadli', 'deaf', 'deal', 'dealer', 'dean', 'death', 'deathofafriend', 'deathpenalti', 'debt', 'debut', 'decad', 'decapit', 'deceas', 'deceit', 'decept', 'decid', 'decis', 'declar', 'dedic', 'deed', 'deep', 'deeper', 'deepli', 'defeat', 'defend', 'defens', 'defi', 'deliv', 'delus', 'demand', 'demimoor', 'demon', 'demonicpossess', 'demons', 'deni', 'dennisdugan', 'dennishopp', 'dennisquaid', 'dentist', 'denzelwashington', 'depart', 'depend', 'depict', 'depress', 'deputi', 'derang', 'derek', 'descend', 'desert', 'design', 'desir', 'desol', 'despair', 'desper', 'despit', 'destin', 'destini', 'destiny', 'destroy', 'destroyed', 'destruct', 'destruction', 'detect', 'detective', 'determin', 'detroit', 'devast', 'develop', 'devic', 'devil', 'devis', 'devot', 'diabol', 'dialogu', 'diamond', 'dianekeaton', 'dianekrug', 'dianelan', 'diari', 'dick', 'dictat', 'did', 'didn', 'die', 'diego', 'dies', 'differ', 'different', 'difficult', 'dig', 'diner', 'dinner', 'dinosaur', 'dire', 'direct', 'director', 'dirti', 'dirtycop', 'disabl', 'disappear', 'disast', 'disaster', 'discov', 'discoveri', 'diseas', 'disease', 'disfigur', 'disgrac', 'disguis', 'disney', 'disord', 'dispatch', 'disrupt', 'distant', 'district', 'disturb', 'diva', 'dive', 'divid', 'divis', 'divorc', 'divorce', 'dna', 'doc', 'doctor', 'document', 'documentari', 'doe', 'doesn', 'dog', 'doll', 'dollar', 'dolphin', 'domest', 'domin', 'don', 'donaldpetri', 'donaldsutherland', 'doncheadl', 'donnel', 'doom', 'door', 'doubl', 'double', 'doublecross', 'doublelif', 'doubt', 'doug', 'dr', 'dracula', 'drag', 'dragon', 'drama', 'dramat', 'draw', 'drawn', 'dread', 'dream', 'dreams', 'dress', 'drew', 'drewbarrymor', 'drifter', 'drink', 'drive', 'driven', 'driver', 'drop', 'drown', 'drug', 'drugabus', 'drugaddict', 'drugdeal', 'druglord', 'drugs', 'drugsmuggl', 'drugtraff', 'drunk', 'drunken', 'du', 'dualident', 'dude', 'duel', 'duke', 'dump', 'duo', 'dure', 'duringcreditssting', 'dustinhoffman', 'dutch', 'duti', 'dwaynejohnson', 'dyinganddeath', 'dylan', 'dynam', 'dysfunctionalfamili', 'dystopia', 'dystopicfutur', 'eager', 'earli', 'earlier', 'earn', 'earth', 'earthquak', 'easi', 'east', 'eat', 'eccentr', 'econom', 'economi', 'eddi', 'eddiemurphi', 'edg', 'edharri', 'editor', 'educ', 'edward', 'edwardburn', 'edwardnorton', 'effect', 'effort', 'egg', 'ego', 'egypt', 'el', 'elabor', 'elderli', 'elect', 'element', 'elev', 'eliaskotea', 'elijahwood', 'elimin', 'elit', 'elizabeth', 'elizabethbank', 'ella', 'elli', 'elliot', 'els', 'elud', 'elus', 'elv', 'elvi', 'embark', 'embassi', 'embroil', 'emerg', 'emigr', 'emilehirsch', 'emili', 'emilyblunt', 'emilymortim', 'emilywatson', 'emma', 'emmaston', 'emmawatson', 'emot', 'emperor', 'empire', 'employ', 'employe', 'enabl', 'encount', 'encourag', 'end', 'endoftheworld', 'endur', 'enemi', 'enemies', 'enemy', 'energi', 'enforc', 'engag', 'engin', 'england', 'english', 'enigmat', 'enjoy', 'enlist', 'ensemblecast', 'ensu', 'ensues', 'ensur', 'entangl', 'enter', 'enterpris', 'entertain', 'entir', 'entiti', 'environ', 'environment', 'epic', 'epidem', 'episod', 'equal', 'era', 'eric', 'ericbana', 'erin', 'ernest', 'erotic', 'erupt', 'escap', 'escapad', 'escape', 'escort', 'especi', 'espionag', 'establish', 'estat', 'estrang', 'etern', 'ethan', 'ethanhawk', 'ethic', 'europ', 'european', 'eva', 'evacu', 'evad', 'evamend', 'eve', 'event', 'events', 'eventu', 'everi', 'everybodi', 'everyday', 'everyon', 'everyth', 'evid', 'evil', 'evolut', 'evolv', 'ewanmcgregor', 'ex', 'exact', 'exactli', 'examin', 'exchang', 'excit', 'execut', 'exhibit', 'exist', 'existence', 'existenti', 'exorc', 'exot', 'exoticisland', 'expect', 'expected', 'expedit', 'experi', 'experienc', 'experiment', 'expert', 'explain', 'explod', 'exploit', 'explor', 'explos', 'expos', 'extramaritalaffair', 'extraordinari', 'extraterrestri', 'extraterrestrialtechnolog', 'extrem', 'extremeviol', 'eye', 'fabl', 'fac', 'face', 'fact', 'faction', 'factori', 'fade', 'fail', 'fairi', 'fairytal', 'faith', 'fake', 'fall', 'fallen', 'fallinginlov', 'falseident', 'fame', 'famili', 'families', 'family', 'familyrelationship', 'famkejanssen', 'famou', 'fan', 'fangvamp', 'fantasi', 'fantast', 'fantasyworld', 'far', 'farm', 'farmer', 'fascin', 'fashion', 'fast', 'fat', 'fatal', 'fate', 'father', 'fatherdaughterrelationship', 'fathersonrelationship', 'favor', 'favorit', 'fbi', 'fbiagent', 'fear', 'fearsom', 'featur', 'feder', 'feel', 'feet', 'fellow', 'femal', 'female', 'femalefriendship', 'femalenud', 'femaleprotagonist', 'fend', 'festiv', 'feud', 'fi', 'fiancé', 'fiction', 'fictionalplac', 'field', 'fierc', 'fight', 'fighter', 'figur', 'file', 'film', 'filmdirector', 'filmmak', 'filmproduc', 'films', 'final', 'financ', 'financi', 'fine', 'finish', 'firm', 'fish', 'fisherman', 'fistfight', 'fit', 'fix', 'flame', 'flashback', 'flat', 'flee', 'flesh', 'fli', 'flight', 'fling', 'flint', 'flirt', 'flood', 'florida', 'flower', 'flyingsauc', 'focu', 'focus', 'foe', 'foil', 'folk', 'follow', 'food', 'foot', 'footag', 'footbal', 'footchas', 'forbidden', 'forbiddenlov', 'forc', 'force', 'forces', 'ford', 'foreign', 'forest', 'forestwhitak', 'forev', 'forever', 'forg', 'forget', 'forgiv', 'form', 'formid', 'formula', 'fort', 'fortun', 'fortune', 'forward', 'foster', 'fought', 'foundfootag', 'fourth', 'fox', 'frame', 'franc', 'france', 'francisco', 'francisfordcoppola', 'frank', 'frankenstein', 'franki', 'frantic', 'fratern', 'fraud', 'freak', 'fred', 'freddi', 'freddieprinzejr', 'free', 'freedom', 'freez', 'french', 'frequent', 'fresh', 'freshman', 'friend', 'friendli', 'friends', 'friendship', 'frighten', 'frog', 'frontier', 'frustrat', 'fu', 'fuel', 'fugit', 'fulfil', 'fulli', 'fun', 'fund', 'funer', 'futur', 'future', 'futurist', 'ga', 'gabrielbyrn', 'gain', 'galaxi', 'gambl', 'gambler', 'game', 'games', 'gang', 'gangster', 'garag', 'garden', 'gari', 'garyoldman', 'garysinis', 'gasstat', 'gather', 'gave', 'gay', 'genehackman', 'gener', 'general', 'genet', 'geniu', 'genius', 'geoffreyrush', 'georg', 'george', 'georgeclooney', 'georgia', 'gerardbutl', 'german', 'germani', 'germany', 'getaway', 'ghetto', 'ghost', 'giant', 'gift', 'girl', 'girlfriend', 'girls', 'given', 'glass', 'global', 'globe', 'glori', 'goal', 'god', 'goe', 'gold', 'golden', 'golf', 'gone', 'good', 'goodvsevil', 'gordon', 'gore', 'gorgeou', 'gorilla', 'got', 'gotham', 'govern', 'government', 'governor', 'grace', 'grade', 'gradual', 'graduat', 'grand', 'grandfath', 'grandfather', 'grandmoth', 'grandmother', 'grant', 'grave', 'great', 'greater', 'greatest', 'greec', 'greed', 'greek', 'green', 'greg', 'gregkinnear', 'grew', 'grief', 'griev', 'griffin', 'grim', 'grip', 'grisli', 'ground', 'group', 'groupoffriend', 'grow', 'grown', 'gruesom', 'guard', 'guardian', 'guerrilla', 'guest', 'guid', 'guilt', 'guitar', 'gun', 'gunfight', 'gunsling', 'guru', 'gusvans', 'guy', 'guypearc', 'guys', 'gwynethpaltrow', 'gypsi', 'ha', 'hack', 'hacker', 'hair', 'half', 'hall', 'halleberri', 'halloween', 'hallucin', 'han', 'hand', 'hands', 'handsom', 'handtohandcombat', 'hang', 'hannah', 'happen', 'happi', 'happili', 'happiness', 'happy', 'harass', 'harbor', 'hard', 'harlem', 'harold', 'haroldrami', 'harri', 'harrisonford', 'harsh', 'harvard', 'harvey', 'harveykeitel', 'hasn', 'hatch', 'hate', 'haunt', 'hauntedhous', 'haven', 'havoc', 'hawaii', 'haydenchristensen', 'head', 'heal', 'health', 'hear', 'heart', 'heartbreak', 'heat', 'heather', 'heathledg', 'heaven', 'heir', 'heiress', 'heist', 'held', 'helen', 'helenabonhamcart', 'helenmirren', 'helicopt', 'hell', 'help', 'henri', 'hero', 'heroes', 'heroic', 'heroin', 'hi', 'hidden', 'hide', 'high', 'highli', 'highschool', 'highschoolsport', 'highschoolstud', 'highway', 'hijack', 'hilari', 'hill', 'himalaya', 'hip', 'hire', 'histor', 'histori', 'historicalfigur', 'history', 'hit', 'hitchhik', 'hitman', 'ho', 'hockey', 'hold', 'hole', 'holiday', 'hollywood', 'home', 'homeinvas', 'homeland', 'homeless', 'homelessperson', 'hometown', 'homicid', 'homosexu', 'honey', 'honeymoon', 'hong', 'honor', 'hood', 'hoodlum', 'hook', 'hop', 'hope', 'hopelessli', 'hopper', 'hord', 'horribl', 'horrif', 'horrifi', 'horror', 'hors', 'horserac', 'hospit', 'hospital', 'host', 'hostag', 'hostage', 'hostil', 'hot', 'hotel', 'hotelroom', 'hour', 'hous', 'house', 'housewif', 'howard', 'howev', 'huge', 'hugh', 'hughgrant', 'hughjackman', 'human', 'humananimalrelationship', 'humanity', 'humankind', 'humans', 'humili', 'humor', 'hundr', 'hunger', 'hungri', 'hunt', 'hunter', 'husband', 'hustler', 'hypnosi', 'hyun', 'ianmckellen', 'ice', 'icecub', 'icon', 'idea', 'ideal', 'idealist', 'ident', 'identity', 'idol', 'idyl', 'ignit', 'ignor', 'ii', 'iii', 'il', 'ill', 'illeg', 'illegalimmigr', 'illegalprostitut', 'illness', 'imag', 'imagin', 'imaginari', 'imagined', 'imax', 'immedi', 'immens', 'immigr', 'immort', 'impact', 'imperi', 'imperson', 'import', 'imposs', 'impress', 'imprison', 'inadvert', 'incest', 'incid', 'includ', 'increas', 'increasingli', 'incred', 'independ', 'independentfilm', 'india', 'indian', 'indiana', 'indianlead', 'individu', 'industri', 'inexplic', 'infam', 'infect', 'infidel', 'infiltr', 'influenc', 'inform', 'inhabit', 'inherit', 'initi', 'inject', 'injur', 'injuri', 'inmat', 'inner', 'innoc', 'insan', 'insecur', 'insid', 'insist', 'inspector', 'inspir', 'instal', 'instant', 'instantli', 'instead', 'instinct', 'instructor', 'insur', 'insurg', 'intellig', 'intend', 'intens', 'intent', 'intern', 'internet', 'interrog', 'intertwin', 'interview', 'intim', 'intrigu', 'introduc', 'invad', 'invas', 'invent', 'inventor', 'invest', 'investig', 'invis', 'invit', 'involv', 'iowa', 'ira', 'iraq', 'ireland', 'irish', 'iron', 'island', 'isn', 'isol', 'isra', 'israel', 'issu', 'itali', 'italian', 'jack', 'jackblack', 'jacki', 'jackiechan', 'jacknicholson', 'jackson', 'jail', 'jake', 'jakegyllenha', 'jame', 'james', 'jamescaan', 'jamesfranco', 'jamesmarsden', 'jamesmcavoy', 'jameswood', 'jami', 'jamiefoxx', 'jamieleecurti', 'jane', 'japan', 'japanes', 'jason', 'jasonbateman', 'jasonbigg', 'jasonle', 'jasonsegel', 'jasonstatham', 'javierbardem', 'jay', 'jazz', 'jealousi', 'jean', 'jedi', 'jeff', 'jeffbridg', 'jeffdaniel', 'jeffgoldblum', 'jennif', 'jenniferaniston', 'jenniferconnelli', 'jennifergarn', 'jenniferjasonleigh', 'jenniferlawr', 'jenniferlopez', 'jerri', 'jersey', 'jess', 'jesseeisenberg', 'jessicaalba', 'jessicabiel

In [233]:
from sklearn.metrics.pairwise import cosine_similarity # cosine similarity is 1/angle between them -- euclidean distance fail on large dimensions

In [234]:
similarity = cosine_similarity(vector)

In [235]:
similarity

array([[1.        , 0.08964215, 0.09258201, ..., 0.04829453, 0.        ,
        0.        ],
       [0.08964215, 1.        , 0.06454972, ..., 0.02525381, 0.        ,
        0.02727724],
       [0.09258201, 0.06454972, 1.        , ..., 0.02608203, 0.        ,
        0.        ],
       ...,
       [0.04829453, 0.02525381, 0.02608203, ..., 1.        , 0.04307305,
        0.04408667],
       [0.        , 0.        , 0.        , ..., 0.04307305, 1.        ,
        0.09304842],
       [0.        , 0.02727724, 0.        , ..., 0.04408667, 0.09304842,
        1.        ]])

In [251]:
list(enumerate(similarity[0]))

[(0, 1.0),
 (1, 0.08964214570007951),
 (2, 0.09258200997725513),
 (3, 0.07807200583588264),
 (4, 0.2038588765750502),
 (5, 0.11501092655705902),
 (6, 0.04259177099999598),
 (7, 0.15289415743128765),
 (8, 0.06506000486323554),
 (9, 0.1019294382875251),
 (10, 0.10826639239215334),
 (11, 0.09968895725584535),
 (12, 0.0994490316197694),
 (13, 0.04733810683311508),
 (14, 0.13710212427677043),
 (15, 0.07171371656006362),
 (16, 0.0857142857142857),
 (17, 0.14675987714106858),
 (18, 0.10030135678562992),
 (19, 0.09200874124564722),
 (20, 0.06121333677828399),
 (21, 0.11595420713048966),
 (22, 0.07559289460184544),
 (23, 0.09258200997725513),
 (24, 0.0563436169819011),
 (25, 0.03827795011754763),
 (26, 0.16035674514745463),
 (27, 0.20149814827784024),
 (28, 0.12344267996967351),
 (29, 0.06837634587578276),
 (30, 0.06965451903188581),
 (31, 0.16903085094570333),
 (32, 0.08877935232369503),
 (33, 0.10141851056742199),
 (34, 0.0),
 (35, 0.1057361065275362),
 (36, 0.1825741858350554),
 (37, 0.08964214570007951),
 (38, 0.08451542547285165),
 (39, 0.08696565534786725),
 (40, 0.08017837257372731),
 (41, 0.17837651700316892),
 (42, 0.0),
 (43, 0.09467621366623016),
 (44, 0.03688555567816587),
 (45, 0.08728715609439694),
 (46, 0.1449427589131121),
 (47, 0.20498001542269692),
 (48, 0.0880237696271323),
 (49, 0.06388765649999398),
 (50, 0.11952286093343935),
 (51, 0.08518354199999197),
 (52, 0.13041013273932528),
 (53, 0.047809144373375745),
 (54, 0.033149677206589796),
 (55, 0.07606982611289638),
 (56, 0.14754222271266348),
 (57, 0.02519763153394848),
 (58, 0.0703210846407743),
 (59, 0.07755667343294811),
 (60, 0.019138975058773815),
 (61, 0.264575131106459),
 (62, 0.09035079029052512),
 (63, 0.09200874124564722),
 (64, 0.03138824102871722),
 (65, 0.020650405139110022),
 (66, 0.023904572186687872),
 (67, 0.18215302221567486),
 (68, 0.12777531299998796),
 (69, 0.027882859227100945),
 (70, 0.08451542547285165),
 (71, 0.07733088933397005),
 (72, 0.14712247158412492),
 (73, 0.036037498507822355),
 (74, 0.2173253797873328),
 (75, 0.11115400287534567),
 (76, 0.07824607964359516),
 (77, 0.015058465048420852),
 (78, 0.057142857142857134),
 (79, 0.06601782722034923),
 (80, 0.05258304820496189),
 (81, 0.11710800875382396),
 (82, 0.0791945516022682),
 (83, 0.1893524273324603),
 (84, 0.12880163722232754),
 (85, 0.120761472884912),
 (86, 0.08226127456606226),
 (87, 0.12143534814378325),
 (88, 0.09583148474999097),
 (89, 0.060717674071891624),
 (90, 0.06506000486323554),
 (91, 0.18215302221567486),
 (92, 0.0654653670707977),
 (93, 0.07644707871564382),
 (94, 0.19518001458970663),
 (95, 0.15118578920369088),
 (96, 0.08226127456606226),
 (97, 0.07319250547113999),
 (98, 0.08964214570007951),
 (99, 0.028988551782622416),
 (100, 0.07377111135633174),
 (101, 0.081199794294115),
 (102, 0.14064216928154863),
 (103, 0.08518354199999197),
 (104, 0.060717674071891624),
 (105, 0.10811249552346706),
 (106, 0.06492654830247076),
 (107, 0.0654653670707977),
 (108, 0.1511857892036909),
 (109, 0.07049073768502413),
 (110, 0.047809144373375745),
 (111, 0.15649215928719035),
 (112, 0.08336550215650926),
 (113, 0.048795003647426664),
 (114, 0.05039526306789696),
 (115, 0.04688072309384954),
 (116, 0.05096471914376255),
 (117, 0.06629935441317959),
 (118, 0.0354384955969167),
 (119, 0.04600437062282361),
 (120, 0.0),
 (121, 0.12143534814378325),
 (122, 0.12555296411486888),
 (123, 0.12073632210407378),
 (124, 0.07100716024967262),
 (125, 0.08571428571428572),
 (126, 0.14085904245475275),
 (127, 0.15311180047019055),
 (128, 0.0),
 (129, 0.09968895725584535),
 (130, 0.02817180849095055),
 (131, 0.1126872339638022),
 (132, 0.047809144373375745),
 (133, 0.030358837035945812),
 (134, 0.13801311186847084),
 (135, 0.0),
 (136, 0.026398183867422733),
 (137, 0.032087396740792626),
 (138, 0.13710212427677043),
 (139, 0.12777531299998796),
 (140, 0.047809144373375745),
 (141, 0.09258200997725513),
 (142, 0.09107651110783743),
 (143, 0.09200874124564722),
 (144, 0.05484084971070818),
 (145, 0.020348923188911988),
 (146, 0.017162482629699223),
 (147, 0.059761430466719674),
 (148, 0.1057361065275362),
 (149, 0.16398401233815754),
 (150, 0.17336567891911936),
 (151, 0.2267786838055363),
 (152, 0.08696565534786725),
 (153, 0.08322503785764788),
 (154, 0.06506000486323554),
 (155, 0.021821789023599235),
 (156, 0.06492654830247076),
 (157, 0.10811249552346706),
 (158, 0.14064216928154863),
 (159, 0.06629935441317959),
 (160, 0.12403473458920844),
 (161, 0.03450327796711771),
 (162, 0.035245368842512066),
 (163, 0.055577001437672836),
 (164, 0.08696565534786725),
 (165, 0.04931136727215379),
 (166, 0.13199091933711365),
 (167, 0.09759000729485331),
 (168, 0.18478728707195913),
 (169, 0.09376144618769908),
 (170, 0.11194341570991125),
 (171, 0.023904572186687872),
 (172, 0.22677868380553634),
 (173, 0.02519763153394848),
 (174, 0.081199794294115),
 (175, 0.07476671794188401),
 (176, 0.030358837035945812),
 (177, 0.0),
 (178, 0.026082026547865053),
 (179, 0.07559289460184544),
 (180, 0.02366905341655754),
 (181, 0.04829452884162951),
 (182, 0.12198750911856666),
 (183, 0.07559289460184544),
 (184, 0.18946618668626833),
 (185, 0.05345224838248488),
 (186, 0.06388765649999398),
 (187, 0.16239958858823),
 (188, 0.023904572186687872),
 (189, 0.12298800925361816),
 (190, 0.089554732567929),
 (191, 0.055577001437672836),
 (192, 0.05039526306789696),
 (193, 0.08247860988423227),
 (194, 0.0),
 (195, 0.061721339984836754),
 (196, 0.05484084971070818),
 (197, 0.03984095364447979),
 (198, 0.059761430466719674),
 (199, 0.09561828874675149),
 (200, 0.11633501014942217),
 (201, 0.0),
 (202, 0.033149677206589796),
 (203, 0.08964214570007951),
 (204, 0.052796367734845466),
 (205, 0.07968190728895957),
 (206, 0.1187013882373396),
 (207, 0.081199794294115),
 (208, 0.1301200097264711),
 (209, 0.07377111135633174),
 (210, 0.0791945516022682),
 (211, 0.025482359571881275),
 (212, 0.07100716024967263),
 (213, 0.06241877839323591),
 (214, 0.0),
 (215, 0.0703210846407743),
 (216, 0.06761234037828133),
 (217, 0.09561828874675149),
 (218, 0.040996003084539386),
 (219, 0.09583148474999097),
 (220, 0.18516401995451026),
 (221, 0.04984447862792268),
 (222, 0.08451542547285165),
 (223, 0.1126872339638022),
 (224, 0.06492654830247076),
 (225, 0.05039526306789696),
 (226, 0.03194382824999699),
 (227, 0.08827348295047496),
 (228, 0.11952286093343936),
 (229, 0.12036162814275589),
 (230, 0.10325202569555011),
 (231, 0.0),
 (232, 0.11952286093343935),
 (233, 0.11065666703449761),
 (234, 0.09200874124564722),
 (235, 0.0791945516022682),
 (236, 0.12143534814378325),
 (237, 0.06900655593423542),
 (238, 0.1203616281427559),
 (239, 0.10174461594455994),
 (240, 0.05039526306789696),
 (241, 0.08827348295047496),
 (242, 0.0857142857142857),
 (243, 0.09759000729485333),
 (244, 0.09759000729485331),
 (245, 0.0857142857142857),
 (246, 0.08081220356417686),
 (247, 0.0),
 (248, 0.04733810683311508),
 (249, 0.14414999403128942),
 (250, 0.0),
 (251, 0.04364357804719847),
 (252, 0.02146693953705459),
 (253, 0.07244179326244427),
 (254, 0.08226127456606226),
 (255, 0.0),
 (256, 0.11952286093343936),
 (257, 0.055577001437672836),
 (258, 0.02219483808092376),
 (259, 0.06388765649999398),
 (260, 0.21971768720102056),
 (261, 0.026082026547865053),
 (262, 0.11720180773462385),
 (263, 0.1057361065275362),
 (264, 0.0),
 (265, 0.028988551782622416),
 (266, 0.10432810619146021),
 (267, 0.07377111135633174),
 (268, 0.05484084971070818),
 (269, 0.03138824102871722),
 (270, 0.09376144618769908),
 (271, 0.07396705090823068),
 (272, 0.029424494316824985),
 (273, 0.02258769757263128),
 (274, 0.09473309334313418),
 (275, 0.15430334996209188),
 (276, 0.07377111135633174),
 (277, 0.0563436169819011),
 (278, 0.09968895725584535),
 (279, 0.07396705090823068),
 (280, 0.0),
 (281, 0.06900655593423541),
 (282, 0.02366905341655754),
 (283, 0.028571428571428567),
 (284, 0.020060271357125983),
 (285, 0.020650405139110022),
 (286, 0.0832250378576479),
 (287, 0.02742042485535409),
 (288, 0.028988551782622416),
 (289, 0.048795003647426664),
 (290, 0.07049073768502413),
 (291, 0.05413319619607667),
 (292, 0.09416472308615166),
 (293, 0.030860669992418377),
 (294, 0.1494035761667992),
 (295, 0.10968169942141635),
 (296, 0.04293387907410918),
 (297, 0.047809144373375745),
 (298, 0.0),
 (299, 0.06241877839323591),
 (300, 0.18478728707195913),
 (301, 0.09824718648648241),
 (302, 0.07559289460184544),
 (303, 0.029424494316824985),
 (304, 0.06877767783794073),
 (305, 0.20328927815368153),
 (306, 0.0857142857142857),
 (307, 0.11492409307804574),
 (308, 0.07049073768502413),
 (309, 0.06629935441317959),
 (310, 0.032087396740792626),
 (311, 0.1583891032045364),
 (312, 0.10826639239215334),
 (313, 0.05797710356524483),
 (314, 0.0),
 (315, 0.08696565534786725),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.10811249552346706),
 (320, 0.035245368842512066),
 (321, 0.0),
 (322, 0.2193633988428327),
 (323, 0.03253000243161777),
 (324, 0.02672612419124244),
 (325, 0.1057361065275362),
 (326, 0.059761430466719674),
 (327, 0.028988551782622416),
 (328, 0.029880715233359837),
 (329, 0.08226127456606226),
 (330, 0.10559273546969093),
 (331, 0.09561828874675149),
 (332, 0.11428571428571427),
 (333, 0.027066598098038335),
 (334, 0.10432810619146021),
 (335, 0.04829452884162951),
 (336, 0.07207499701564471),
 (337, 0.04733810683311508),
 (338, 0.0),
 (339, 0.0515539262226467),
 (340, 0.052796367734845466),
 (341, 0.0857142857142857),
 (342, 0.17008401285415226),
 (343, 0.020650405139110022),
 (344, 0.030860669992418377),
 (345, 0.024397501823713332),
 (346, 0.0),
 (347, 0.0),
 (348, 0.06761234037828133),
 (349, 0.08964214570007951),
 (350, 0.052164053095730106),
 (351, 0.0),
 (352, 0.028571428571428567),
 (353, 0.0447773662839645),
 (354, 0.02258769757263128),
 (355, 0.03903600291794132),
 (356, 0.09759000729485331),
 (357, 0.0),
 (358, 0.06388765649999398),
 (359, 0.033149677206589796),
 (360, 0.02219483808092376),
 (361, 0.0791945516022682),
 (362, 0.0994490316197694),
 (363, 0.10647942749998995),
 (364, 0.024397501823713332),
 (365, 0.08017837257372731),
 (366, 0.059761430466719674),
 (367, 0.0),
 (368, 0.13522468075656266),
 (369, 0.08827348295047496),
 (370, 0.05345224838248488),
 (371, 0.1019294382875251),
 (372, 0.04984447862792268),
 (373, 0.18018749253911176),
 (374, 0.03984095364447979),
 (375, 0.06440081861116377),
 (376, 0.04931136727215379),
 (377, 0.0),
 (378, 0.0),
 (379, 0.0528680532637681),
 (380, 0.0563436169819011),
 (381, 0.09376144618769908),
 (382, 0.0),
 (383, 0.04688072309384954),
 (384, 0.03138824102871722),
 (385, 0.0),
 (386, 0.023002185311411804),
 (387, 0.025482359571881275),
 (388, 0.0),
 (389, 0.10141851056742199),
 (390, 0.02817180849095055),
 (391, 0.059350694118669806),
 (392, 0.03194382824999699),
 (393, 0.0),
 (394, 0.02577696311132335),
 (395, 0.0563436169819011),
 (396, 0.04688072309384954),
 (397, 0.05413319619607667),
 (398, 0.0),
 (399, 0.02519763153394848),
 (400, 0.09416472308615166),
 (401, 0.03253000243161777),
 (402, 0.08827348295047496),
 (403, 0.08728715609439694),
 (404, 0.06506000486323554),
 (405, 0.06277648205743444),
 (406, 0.022005942406783077),
 (407, 0.027066598098038335),
 (408, 0.035245368842512066),
 (409, 0.0),
 (410, 0.1019294382875251),
 (411, 0.057142857142857134),
 (412, 0.10079052613579392),
 (413, 0.1494035761667992),
 (414, 0.03194382824999699),
 (415, 0.0628970902033151),
 (416, 0.05413319619607667),
 (417, 0.03450327796711771),
 (418, 0.03877833671647406),
 (419, 0.07244179326244427),
 (420, 0.11952286093343936),
 (421, 0.024397501823713332),
 (422, 0.12344267996967351),
 (423, 0.04364357804719847),
 (424, 0.039567129412446535),
 (425, 0.06716604942594674),
 (426, 0.05778855963970646),
 (427, 0.03194382824999699),
 (428, 0.05894831189188944),
 (429, 0.0),
 (430, 0.05345224838248488),
 (431, 0.025482359571881275),
 (432, 0.12598815766974242),
 (433, 0.03253000243161777),
 (434, 0.0),
 (435, 0.040996003084539386),
 (436, 0.0),
 (437, 0.02742042485535409),
 (438, 0.12741179785940637),
 (439, 0.02817180849095055),
 (440, 0.026398183867422733),
 (441, 0.060717674071891624),
 (442, 0.04829452884162951),
 (443, 0.06658451424277127),
 (444, 0.0),
 (445, 0.1031078524452934),
 (446, 0.024655683636076894),
 (447, 0.06837634587578276),
 (448, 0.02238868314198225),
 (449, 0.11595420713048966),
 (450, 0.02219483808092376),
 (451, 0.026398183867422733),
 (452, 0.03194382824999699),
 (453, 0.027066598098038335),
 (454, 0.1246111965698067),
 (455, 0.06388765649999398),
 (456, 0.04600437062282361),
 (457, 0.09258200997725513),
 (458, 0.04600437062282361),
 (459, 0.03688555567816587),
 (460, 0.02577696311132335),
 (461, 0.15430334996209188),
 (462, 0.036037498507822355),
 (463, 0.03450327796711771),
 (464, 0.0),
 (465, 0.0),
 (466, 0.15118578920369088),
 (467, 0.11194341570991125),
 (468, 0.030358837035945812),
 (469, 0.0628970902033151),
 (470, 0.04733810683311508),
 (471, 0.06776309271789384),
 (472, 0.1126872339638022),
 (473, 0.09862273454430757),
 (474, 0.0),
 (475, 0.045584230583855176),
 (476, 0.14414999403128942),
 (477, 0.0),
 (478, 0.057416925176321444),
 (479, 0.09221388919541468),
 (480, 0.10432810619146021),
 (481, 0.0),
 (482, 0.02366905341655754),
 (483, 0.1301200097264711),
 (484, 0.030860669992418377),
 (485, 0.055577001437672836),
 (486, 0.08409599149190805),
 (487, 0.13259870882635919),
 (488, 0.07011073093994918),
 (489, 0.0),
 (490, 0.15118578920369088),
 (491, 0.10821091383745125),
 (492, 0.0791945516022682),
 (493, 0.03283545516515592),
 (494, 0.0),
 (495, 0.19889806323953876),
 (496, 0.0),
 (497, 0.0),
 (498, 0.07207499701564471),
 (499, 0.0),
 (500, 0.02817180849095055),
 (501, 0.08586775814821836),
 (502, 0.14488358652488853),
 (503, 0.08451542547285165),
 (504, 0.0),
 (505, 0.14754222271266348),
 (506, 0.03688555567816587),
 (507, 0.27602622373694163),
 (508, 0.10690449676496976),
 (509, 0.023218173010628604),
 (510, 0.10559273546969093),
 (511, 0.09583148474999097),
 (512, 0.033149677206589796),
 (513, 0.16239958858823),
 (514, 0.052164053095730106),
 (515, 0.026398183867422733),
 (516, 0.029880715233359837),
 (517, 0.0),
 (518, 0.04984447862792268),
 (519, 0.0),
 (520, 0.0),
 (521, 0.027066598098038335),
 (522, 0.026082026547865053),
 (523, 0.052164053095730106),
 (524, 0.0),
 (525, 0.04984447862792268),
 (526, 0.030358837035945812),
 (527, 0.03877833671647406),
 (528, 0.024397501823713332),
 (529, 0.17837651700316892),
 (530, 0.05797710356524483),
 (531, 0.05039526306789696),
 (532, 0.022792115291927588),
 (533, 0.06277648205743444),
 (534, 0.08728715609439694),
 (535, 0.1031078524452934),
 (536, 0.11952286093343936),
 (537, 0.07755667343294811),
 (538, 0.0),
 (539, 0.26089696604360174),
 (540, 0.0791945516022682),
 (541, 0.08877935232369503),
 (542, 0.039567129412446535),
 (543, 0.08226127456606226),
 (544, 0.060717674071891624),
 (545, 0.026082026547865053),
 (546, 0.07207499701564471),
 (547, 0.09107651110783743),
 (548, 0.0),
 (549, 0.12741179785940637),
 (550, 0.026082026547865053),
 (551, 0.040697846377823976),
 (552, 0.0),
 (553, 0.03138824102871722),
 (554, 0.0),
 (555, 0.04688072309384954),
 (556, 0.02817180849095055),
 (557, 0.13041013273932528),
 (558, 0.0),
 (559, 0.03194382824999699),
 (560, 0.03827795011754763),
 (561, 0.033149677206589796),
 (562, 0.03194382824999699),
 (563, 0.02672612419124244),
 (564, 0.09258200997725513),
 (565, 0.045584230583855176),
 (566, 0.025482359571881275),
 (567, 0.026398183867422733),
 (568, 0.14712247158412492),
 (569, 0.05039526306789696),
 (570, 0.07207499701564471),
 (571, 0.04438967616184752),
 (572, 0.11396057645963793),
 (573, 0.02164218276749025),
 (574, 0.02492223931396134),
 (575, 0.04829452884162951),
 (576, 0.055577001437672836),
 (577, 0.20916500663351886),
 (578, 0.04517539514526256),
 (579, 0.15179418517972906),
 (580, 0.026082026547865053),
 (581, 0.15694120514358612),
 (582, 0.25539990311691463),
 (583, 0.040120542714251965),
 (584, 0.08451542547285165),
 (585, 0.02672612419124244),
 (586, 0.047809144373375745),
 (587, 0.07733088933397005),
 (588, 0.02817180849095055),
 (589, 0.13801311186847082),
 (590, 0.03253000243161777),
 (591, 0.06658451424277127),
 (592, 0.023002185311411804),
 (593, 0.0),
 (594, 0.05345224838248488),
 (595, 0.17638342073763935),
 (596, 0.09658905768325902),
 (597, 0.06277648205743444),
 (598, 0.03779644730092272),
 (599, 0.028988551782622416),
 (600, 0.07244179326244427),
 (601, 0.035834468731623305),
 (602, 0.09467621366623016),
 (603, 0.05884898863364997),
 (604, 0.06900655593423542),
 (605, 0.030358837035945812),
 (606, 0.0),
 (607, 0.06195121541733006),
 (608, 0.0),
 (609, 0.04931136727215379),
 (610, 0.06198013080533033),
 (611, 0.024655683636076894),
 (612, 0.06716604942594674),
 (613, 0.03984095364447979),
 (614, 0.0515539262226467),
 (615, 0.06506000486323554),
 (616, 0.03688555567816587),
 (617, 0.05345224838248488),
 (618, 0.09467621366623016),
 (619, 0.0),
 (620, 0.0),
 (621, 0.07049073768502413),
 (622, 0.023002185311411804),
 (623, 0.0),
 (624, 0.11338934190276817),
 (625, 0.033806170189140665),
 (626, 0.08696565534786725),
 (627, 0.11633501014942217),
 (628, 0.0),
 (629, 0.05096471914376255),
 (630, 0.02577696311132335),
 (631, 0.0563436169819011),
 (632, 0.081199794294115),
 (633, 0.02492223931396134),
 (634, 0.07824607964359516),
 (635, 0.07100716024967263),
 (636, 0.024655683636076894),
 (637, 0.02519763153394848),
 (638, 0.035245368842512066),
 (639, 0.0),
 (640, 0.06388765649999398),
 (641, 0.0),
 (642, 0.0),
 (643, 0.10559273546969093),
 (644, 0.052164053095730106),
 (645, 0.04733810683311508),
 (646, 0.057142857142857134),
 (647, 0.05096471914376255),
 (648, 0.03194382824999699),
 (649, 0.0),
 (650, 0.05484084971070818),
 (651, 0.0),
 (652, 0.045584230583855176),
 (653, 0.11338934190276817),
 (654, 0.11002971203391539),
 (655, 0.02519763153394848),
 (656, 0.0),
 (657, 0.03710709253896555),
 (658, 0.052164053095730106),
 (659, 0.026398183867422733),
 (660, 0.0994490316197694),
 (661, 0.1760475392542646),
 (662, 0.0),
 (663, 0.0),
 (664, 0.06277648205743444),
 (665, 0.07644707871564382),
 (666, 0.05345224838248488),
 (667, 0.0),
 (668, 0.14414999403128942),
 (669, 0.03688555567816587),
 (670, 0.018553546269482774),
 (671, 0.07319250547113999),
 (672, 0.030860669992418377),
 (673, 0.02129588549999799),
 (674, 0.07824607964359516),
 (675, 0.04733810683311508),
 (676, 0.029880715233359837),
 (677, 0.026398183867422733),
 (678, 0.12143534814378325),
 (679, 0.0),
 (680, 0.07824607964359516),
 (681, 0.028988551782622416),
 (682, 0.020965696734438367),
 (683, 0.052164053095730106),
 (684, 0.0),
 (685, 0.033806170189140665),
 (686, 0.033806170189140665),
 (687, 0.11769797726729994),
 (688, 0.045584230583855176),
 (689, 0.0),
 (690, 0.027066598098038335),
 (691, 0.061721339984836754),
 (692, 0.11501092655705902),
 (693, 0.036037498507822355),
 (694, 0.023218173010628604),
 (695, 0.07559289460184544),
 (696, 0.02344036154692477),
 (697, 0.0),
 (698, 0.04643634602125721),
 (699, 0.03984095364447979),
 (700, 0.029880715233359837),
 (701, 0.06629935441317959),
 (702, 0.024147264420814756),
 (703, 0.02238868314198225),
 (704, 0.07100716024967263),
 (705, 0.025482359571881275),
 (706, 0.023002185311411804),
 (707, 0.0),
 (708, 0.026082026547865053),
 (709, 0.02146693953705459),
 (710, 0.060609152673132646),
 (711, 0.055577001437672836),
 (712, 0.0),
 (713, 0.026398183867422733),
 (714, 0.0),
 (715, 0.10350983390135313),
 (716, 0.028571428571428567),
 (717, 0.0),
 (718, 0.047809144373375745),
 (719, 0.0),
 (720, 0.027788500718836418),
 (721, 0.033806170189140665),
 (722, 0.0),
 (723, 0.026082026547865053),
 (724, 0.02492223931396134),
 (725, 0.0),
 (726, 0.0),
 (727, 0.03223291856101521),
 (728, 0.07644707871564382),
 (729, 0.05345224838248488),
 (730, 0.036454130828824455),
 (731, 0.05413319619607667),
 (732, 0.07319250547113999),
 (733, 0.06440081861116377),
 (734, 0.07171371656006362),
 (735, 0.07476671794188401),
 (736, 0.03253000243161777),
 (737, 0.08017837257372731),
 (738, 0.0),
 (739, 0.042257712736425826),

In [262]:
def recommend(movie):
    index = new_df[new_df['original_title'] == movie].index[0]   # index of any movie can be taken
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1]) 
    # sorting the similarity array based on distance 
    # rev will do in desc order
    # enumerate will assign index to each similarity(0,1 : 1, 0.008) (movie x ka movie wih index 0 ke saath similarity and so on)
    # lambda function to sort movie based on x[1] , second entry i.e similarity not indexes
    for i in distances[1:6]:
        print(new_df.iloc[i[0]].original_title)

In [263]:
new_df[new_df['original_title'] == 'Batman Begins'].index[0]       # how index of any movie can be taken

119

In [264]:
recommend('Avatar')

Aliens vs Predator: Requiem
Independence Day
Falcon Rising
Jupiter Ascending
Titan A.E.

In [255]:
pickle.dump(new_df,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))

In [252]:
import pickle